server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ultimatum_db?serverTimezone=Asia/Seoul
    username: ultimatum
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  kakao:
    client_id: 100bde42d2ac4c0bf9cf54655e5395cc
    redirect_uri: http://localhost:8080/kakaologin
  config:
    import: classpath:aws.yml, classpath:secretmanage.yml
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

